srcswap.exe : ../source/srcswap.cpp
	g++ -c ../source/srcswap.cpp
	g++ -o srcswap srcswap.o
	del srcswap.o
	
	
pcxtopcl.exe : ../source/pcxtopcl.cpp
	g++ -c ../source/pcxtopcl.cpp
	g++ -o pcxtopcl pcxtopcl.o
	del pcxtopcl.o
	

	
pdbcmp.exe : ../source/pdbcmp.c
	gcc -c ../source/pdbcmp.c
	gcc -o pdbcmp pdbcmp.o
	del pdbcmp.o
	
	

srcfix.exe : ../source/srcfix.c
	gcc -c ../source/srcfix.c
	gcc -o srcfix srcfix.o
	del srcfix.o